2017/10/05 13:53:32 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:34 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:35 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:35 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:35 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:36 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:36 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:53:37 [error] 20273#20273: *2 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:56:06 [error] 20273#20273: *11 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:56:08 [error] 20273#20273: *11 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 13:56:09 [error] 20273#20273: *11 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (111: Connection refused) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 14:04:31 [crit] 20273#20273: *19 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (2: No such file or directory) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 14:04:33 [crit] 20273#20273: *19 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (2: No such file or directory) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 15:47:11 [crit] 20877#20877: *122 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (2: No such file or directory) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 15:48:00 [crit] 20877#20877: *122 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (2: No such file or directory) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET /admin/ HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
2017/10/05 15:49:56 [crit] 20877#20877: *122 connect() to unix:/home/ubuntu/Env/djangosite/mysite.sock failed (2: No such file or directory) while connecting to upstream, client: 116.48.87.181, server: django.leo-kwok.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/ubuntu/Env/djangosite/mysite.sock:", host: "django.leo-kwok.com:8080"
